hci_packetizer: fix unused building errors
Fixes the following building errors:

system/bt/vendor_libs/linux/interface/hci_packetizer.cc:28:14:
error: unused variable 'preamble_size_for_type' [-Werror,-Wunused-const-variable]
const size_t preamble_size_for_type[] = {
             ^
system/bt/vendor_libs/linux/interface/hci_packetizer.cc:35:8:
error: unused function 'HciGetPacketLengthForType' [-Werror,-Wunused-function]
size_t HciGetPacketLengthForType(HciPacketType type, const uint8_t* preamble) {
       ^
2 errors generated.